### ISSUE TITLE
Make a separate js file for javascript code.

### ISSUE THREAD

**Issue by VG-1** [VG-1/PlaylistAdda#30] opened 2022-10-03 20:42 UTC

**Comment by Sammydepoj** [comment] 2022-10-03 20:56
Hi, I'll like to work on this. 
Kindly assign it to me

**Comment by VG-1** [comment] 2022-10-03 21:02
Sure @Sammydepoj 
Assigning this to you.

**Comment by Sammydepoj** [comment] 2022-10-03 21:12
Thank you. Will start working on it asap

**Comment by Ayush-Khandelwal28** [comment] 2022-10-04 08:02
If the issue is still open, I would like to contribute, please assign it to me @VG-1

**Comment by Sammydepoj** [comment] 2022-10-04 08:04
Hi @Ayush-Khandelwal28 , I've worked on the issue. Thank you.

**Closed** 2022-10-04 08:14 UTC
Labels: hacktoberfest, hacktoberfest-accepted
